#!/bin/bash

# antoniogamiz/i3wm must exist under ~/.config

REPO=~/.config/i3wm

# ======================================

cp -a ~/.config/i3/ $REPO/i3/
cp -a ~/.config/i3status/ $REPO/i3status
cp -a ~/.config/compton.conf $REPO/compton.conf

# =====================================
# these programs should be moved to a 
# common directory
cp ~/.local/bin/i3exit $REPO/i3exit
cp ~/.local/bin/i3backup $REPO/i3backup
cp ~/.local/bin/ddspawn $REPO/ddspawn

# =====================================

# zshrc config
cp ~/.zshrc $REPO/.zshrc
# replace tokens
sed -i '/TOKEN/c\censored' $REPO/.zshrc

cd $REPO
git add .
git commit -m "Automated backup, $(date)"
git push 
